
package soap.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeWebImplementation", targetNamespace = "http://service.soap/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeWebImplementation {


    /**
     * 
     * @return
     *     returns soap.service.GroupOfEmployee
     */
    @WebMethod
    @WebResult(name = "findAll", partName = "findAll")
    @Action(input = "http://service.soap/EmployeeWebImplementation/readRequest", output = "http://service.soap/EmployeeWebImplementation/readResponse")
    public GroupOfEmployee read();

    /**
     * 
     * @param arg0
     * @return
     *     returns soap.service.Employee
     */
    @WebMethod
    @WebResult(name = "addNewEmployee", partName = "addNewEmployee")
    @Action(input = "http://service.soap/EmployeeWebImplementation/createRequest", output = "http://service.soap/EmployeeWebImplementation/createResponse")
    public Employee create(
        @WebParam(name = "arg0", partName = "arg0")
        Employee arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns soap.service.GroupOfEmployee
     */
    @WebMethod
    @WebResult(name = "findBasedOnPincode", partName = "findBasedOnPincode")
    @Action(input = "http://service.soap/EmployeeWebImplementation/displayBasedOnPincodeRequest", output = "http://service.soap/EmployeeWebImplementation/displayBasedOnPincodeResponse")
    public GroupOfEmployee displayBasedOnPincode(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns soap.service.Employee
     */
    @WebMethod
    @WebResult(name = "findBasedOnId", partName = "findBasedOnId")
    @Action(input = "http://service.soap/EmployeeWebImplementation/displayBasedOnIDRequest", output = "http://service.soap/EmployeeWebImplementation/displayBasedOnIDResponse")
    public Employee displayBasedOnID(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
