
package services.employee;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeePort", targetNamespace = "http://employee.services")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeePort {


    /**
     * 
     * @param filterByIdRequest
     * @return
     *     returns services.employee.FilterByIdResponse
     */
    @WebMethod
    @WebResult(name = "filterByIdResponse", targetNamespace = "http://employee.services", partName = "filterByIdResponse")
    public FilterByIdResponse filterById(
        @WebParam(name = "filterByIdRequest", targetNamespace = "http://employee.services", partName = "filterByIdRequest")
        FilterByIdRequest filterByIdRequest);

    /**
     * 
     * @param findAllEmployeeRequest
     * @return
     *     returns services.employee.FindAllEmployeeResponse
     */
    @WebMethod
    @WebResult(name = "findAllEmployeeResponse", targetNamespace = "http://employee.services", partName = "findAllEmployeeResponse")
    public FindAllEmployeeResponse findAllEmployee(
        @WebParam(name = "findAllEmployeeRequest", targetNamespace = "http://employee.services", partName = "findAllEmployeeRequest")
        FindAllEmployeeRequest findAllEmployeeRequest);

    /**
     * 
     * @param filterByPinRequest
     * @return
     *     returns services.employee.FilterByPinResponse
     */
    @WebMethod
    @WebResult(name = "filterByPinResponse", targetNamespace = "http://employee.services", partName = "filterByPinResponse")
    public FilterByPinResponse filterByPin(
        @WebParam(name = "filterByPinRequest", targetNamespace = "http://employee.services", partName = "filterByPinRequest")
        FilterByPinRequest filterByPinRequest);

    /**
     * 
     * @param createEmployeeRequest
     * @return
     *     returns services.employee.CreateEmployeeResponse
     */
    @WebMethod(operationName = "CreateEmployee")
    @WebResult(name = "CreateEmployeeResponse", targetNamespace = "http://employee.services", partName = "CreateEmployeeResponse")
    public CreateEmployeeResponse createEmployee(
        @WebParam(name = "CreateEmployeeRequest", targetNamespace = "http://employee.services", partName = "CreateEmployeeRequest")
        CreateEmployeeRequest createEmployeeRequest);

}
